# Bước 1: Dùng một Image Python chính thức làm nền tảng
FROM python:3.10-slim

# Bước 2: Tạo một thư mục làm việc bên trong Container
WORKDIR /app

# Bước 3: Copy file list thư viện vào trước và tiến hành cài đặt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Bước 4: Copy toàn bộ code từ máy ngoài vào trong thư mục /app của Container
COPY . .

# Bước 5: Mở port 5000 để máy ngoài có thể truy cập vào App Flask
EXPOSE 5000

# Bước 6: Lệnh để chạy ứng dụng khi Container khởi động
CMD ["python", "app.py"]